Revert "tweak C code"
This reverts commit fa17c5b17d83cda2e0e8165de971188d3129c346.

Causing travis errors, e.g.:

libpdf/buf.c: In function ‘pdf_buf_pack_8_4’:
libpdf/buf.c:8:3: error: ‘for’ loop initial declarations are only allowed in C99 mode